# Generated by Django 4.1.4 on 2022-12-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_user_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='user',
        ),
    ]
